/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package latexexamgenertator;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class QuestionAnswerForm extends javax.swing.JFrame {

    /**
     * Creates new form QuestionAnswerForm
     */
    //public ExamForm ex;
    public Question QSearchFoundat=null;
    public QuestionAnswerForm() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        btg.add(jRadioButton1);
        btg.add(jRadioButton2);
        btg.add(jRadioButton3);
        btg.add(jRadioButton4);
        btg.add(jRadioButton5);
        ExamForm ex=new ExamForm();
        jlblQuestionCounter.setText(ExamForm.AllQuestions.size()+"");
        this.setTitle(this.getTitle()+" "+ LatexExamGenertator.Examiner);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaQuestion = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jbtnSaveInsert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        JbtnSaveGenerateExam = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlblQuestionCounter = new javax.swing.JLabel();
        jbtnSearch = new javax.swing.JButton();
        jtextfeildSearchArea = new javax.swing.JTextField();
        jbtnShowAll = new javax.swing.JButton();
        jbtndelete = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FCIH Exam Generator V 1.0");

        jtxtAreaQuestion.setColumns(20);
        jtxtAreaQuestion.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaQuestion);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jbtnSaveInsert.setText("Sav/Insert Question");
        jbtnSaveInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveInsertActionPerformed(evt);
            }
        });

        jLabel1.setText("Question");

        jLabel2.setText("Answers");

        jRadioButton1.setText("IsCorrect");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("IsCorrect");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("IsCorrect");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("IsCorrect");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("IsCorrect");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        JbtnSaveGenerateExam.setText("Save and Generate Exam Models");
        JbtnSaveGenerateExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSaveGenerateExamActionPerformed(evt);
            }
        });

        jLabel3.setText("Saved Questions");

        jlblQuestionCounter.setText("jLabel4");

        jbtnSearch.setText("Search Questions");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jtextfeildSearchArea.setText("Search");
        jtextfeildSearchArea.setName("txtSearch"); // NOI18N

        jbtnShowAll.setText("Show All");
        jbtnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowAllActionPerformed(evt);
            }
        });

        jbtndelete.setText("Delete");
        jbtndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeleteActionPerformed(evt);
            }
        });

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnUpdate)
                                    .addComponent(jbtndelete))
                                .addContainerGap(72, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jbtnSaveInsert))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtextfeildSearchArea, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtnSearch))
                                    .addComponent(JbtnSaveGenerateExam))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnShowAll))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(73, 73, 73)
                                .addComponent(jlblQuestionCounter)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlblQuestionCounter))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnSaveInsert)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtndelete))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextfeildSearchArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch)
                    .addComponent(jbtnShowAll))
                .addGap(18, 18, 18)
                .addComponent(JbtnSaveGenerateExam)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void InsertQuestion()
    {
        try {
            // TODO add your handling code here:
            Question q=new Question();
            q.Desc=jtxtAreaQuestion.getText();
            int ParentId=q.InserQuestion();
            if (ParentId==0)
            {
                JOptionPane.showMessageDialog(null, "Duplicate Question", "Duplication Error", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
            Answer a=new Answer();
            a.Desc=jTextField1.getText();
            a.InsertAnswer(ParentId,jRadioButton1.isSelected());
            a=new Answer();
            a.Desc=jTextField2.getText();
            a.InsertAnswer(ParentId,jRadioButton2.isSelected());
             a=new Answer();
            a.Desc=jTextField3.getText();
            a.InsertAnswer(ParentId,jRadioButton3.isSelected());
            a=new Answer();
            a.Desc=jTextField4.getText();
            a.InsertAnswer(ParentId,jRadioButton4.isSelected());
            a=new Answer();
            a.Desc=jTextField5.getText();
            a.InsertAnswer(ParentId,jRadioButton5.isSelected());
            clearUI();
            }
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
        jlblQuestionCounter.setText(ExamForm.AllQuestions.size()+"");
    }
    private void jbtnSaveInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveInsertActionPerformed
    InsertQuestion();
    jbtnShowAll.setText("Show all Questions");
    }//GEN-LAST:event_jbtnSaveInsertActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void JbtnSaveGenerateExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSaveGenerateExamActionPerformed
        try {
            // TODO add your handling code here:
            LatexFileManager ltx=new LatexFileManager(LatexExamGenertator.ExamFolderPath+""+LatexExamGenertator.ExamFileName);
            //ExamForm ex=new ExamForm(LatexExamGenertator.IsDatabase);
            if(LatexExamGenertator.IsDatabase)
            {
                ExamForm.LoadData();
            }
            ltx.GenerateLatex(); 
            ExamForm.SaveBinary();
            jlblQuestionCounter.setText(ExamForm.AllQuestions.size()+"");
            JOptionPane.showMessageDialog(this, "Models and Answer Key Generated");
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_JbtnSaveGenerateExamActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        // TODO add your handling code here:
        /*ListAllQuestuions2 a=new QSearchFoundat=q;
                loadQuestionForm(q);
                
        a.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        a.setVisible(true);
        */
        //searching 
             QSearchFoundat=  ExamForm.SearchQuestions(jtextfeildSearchArea.getText());
             if (QSearchFoundat==null)
             {
             JOptionPane.showMessageDialog(this, "No match found");
             }
             else
             {
                 loadQuestionForm(QSearchFoundat);
             }
        
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jbtnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowAllActionPerformed
        // TODO add your handling code here:
        
        ListAllQuestuions2 a=new ListAllQuestuions2(this);
        a.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        a.setVisible(true);
        
    }//GEN-LAST:event_jbtnShowAllActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
            if (LatexExamGenertator.IsDatabase)
            {
                try {
                    QSearchFoundat.delQuestion();
                } catch (SQLException ex) {
                    Logger.getLogger(QuestionAnswerForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
            ExamForm.AllQuestions.remove(QSearchFoundat);
            }
            InsertQuestion();
                clearUI();
            QSearchFoundat=null;
            JOptionPane.showMessageDialog(this, "Update finished");
jlblQuestionCounter.setText(ExamForm.AllQuestions.size()+"");           
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeleteActionPerformed
        // TODO add your handling code here:
        if (LatexExamGenertator.IsDatabase)
            {
                try {
                    QSearchFoundat.delQuestion();
                } catch (SQLException ex) {
                    Logger.getLogger(QuestionAnswerForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
            ExamForm.AllQuestions.remove(QSearchFoundat);
            }
            clearUI();
            QSearchFoundat=null;
             JOptionPane.showMessageDialog(this, "Delete finished");
jlblQuestionCounter.setText(ExamForm.AllQuestions.size()+"");           
    }//GEN-LAST:event_jbtndeleteActionPerformed
    public  void loadQuestionForm(Question x)
    {
        jtxtAreaQuestion.setText(x.Desc);
        jTextField1.setText(x.ArrayListAnswers.get(0).Desc);
        if (x.ArrayListAnswers.get(0).IsCorrect==1)
        {jRadioButton1.setSelected(true);}
        jTextField2.setText(x.ArrayListAnswers.get(1).Desc);
        if (x.ArrayListAnswers.get(1).IsCorrect==1)
        {jRadioButton2.setSelected(true);}
        jTextField3.setText(x.ArrayListAnswers.get(2).Desc);
        if (x.ArrayListAnswers.get(2).IsCorrect==1)
        {jRadioButton3.setSelected(true);}
        jTextField4.setText(x.ArrayListAnswers.get(3).Desc);
        if (x.ArrayListAnswers.get(3).IsCorrect==1)
        {jRadioButton4.setSelected(true);}
        jTextField5.setText(x.ArrayListAnswers.get(4).Desc);
        if (x.ArrayListAnswers.get(4).IsCorrect==1)
        {jRadioButton5.setSelected(true);}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuestionAnswerForm().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(QuestionAnswerForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(QuestionAnswerForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnSaveGenerateExam;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton jbtnSaveInsert;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnShowAll;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JButton jbtndelete;
    private javax.swing.JLabel jlblQuestionCounter;
    private javax.swing.JTextField jtextfeildSearchArea;
    private javax.swing.JTextArea jtxtAreaQuestion;
    // End of variables declaration//GEN-END:variables
ButtonGroup btg=new ButtonGroup();

public void btn4setTest(String t)
{
    this.jbtnShowAll.setText(t);
}
    private void clearUI() {
            jtxtAreaQuestion.setText(null);
            jTextField1.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
            jTextField4.setText(null);
            jTextField5.setText(null);
            btg.clearSelection();
    }
}
